### ISSUE TITLE
Support de la banque ING

### ISSUE THREAD

**Issue by Parresseman** [zxperts/MonArg#1]
# Description
J'ai voulu chargé un fichier .csv provenant d'ING et une erreur est survenue : 
![image](https://user-images.githubusercontent.com/39089630/167706587-e8181f54-dd66-4562-a576-9d6f7ea38d2a.png)

# Demande
Pouvez-vous mettre en place un support des fichiers ING ? 
Voici les colonnes du fichier : 
* Numéro de compte
* Nom du compte
* Compte partie adverse
* Numéro de mouvement
* Date comptable
* Date valeur
* Montant
* Devise
* Libellés
* Détails du mouvement
* Message

**Comment by zxperts** [comment]
Bonjour,
Merci pour la remarque.
La correction vient d'être faite pour prendre en compte le Libellés.  👍🏾 

zxperts

**Comment by zxperts** [comment]
Nouvelle correction effectuée aujourd'hui.
